@startuml
skinparam componentStyle uml2

participant "Client" as c

participant "Gateway" as gw

participant "OAuth Server" as os

participant "Login JWT" as be

c --> gw : GET /*
c <-- gw : 302 /login

c --> gw : GET /login
c <-- gw : 302 {oauth.server}/auth

c --> os : GET /auth
c <-- os : 200 Auth UI

c --> c : Ask and get credentials

c --> os : POST /getToken + credentials
os --> os : Verify and create OAuth Token

c <-- os : 302 /login + OAuth Token

c --> gw : GET /login + OAuth Token

gw --> os : POST /checkToken + OAuth Token
gw <-- os : 200 Token is valid

gw --> be : POST /getSessionToken
gw <-- be : 200 OK + Session Token
c <-- gw : 200 OK + Session Token

c --> gw : GET /* + Session Token
c <-- gw : 200 /resource


@enduml
